---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workload-deployment
  annotations:
    differ/active: "true"
spec:
  selector:
    matchLabels:
      app: test-workload-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: test-workload-deployment
      annotations:
        differ/active: "true"
    spec:
      containers:
        - name: test-workload-deployment
          image: wiedmannfelix/heartbeat:1.2.0

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-workload-daemonset
  annotations:
    differ/active: "true"
spec:
  selector:
    matchLabels:
      app: test-workload-daemonset
  template:
    metadata:
      labels:
        app: test-workload-daemonset
    spec:
      imagePullSecrets:
        - name: demo
      containers:
        - name: test-workload-daemonset
          image: wiedmannfelix/heartbeat:latest

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-workload-statefulset
  annotations:
    differ/active: "true"
spec:
  serviceName: test-workload-statefulset-svc
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: dummy
          image: tomcat

---
apiVersion: v1
kind: Service
metadata:
  name: test-workload-statefulset-svc
spec:
  clusterIP: None
  selector:
    app: test-workload-daemonset
  ports:
    - port: 8080
      targetPort: 80