apiVersion: apps/v1
kind: Deployment
metadata:
  name: differ-deployment
  annotations:
    differ/active: "true"
spec:
  selector:
    matchLabels:
      app: differ
  template:
    metadata:
      labels:
        app: differ
    spec:
      serviceAccountName: differ
      containers:
      - name: differ
        image: differ:dev
        args: ["--loglevel","debug"]
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        volumeMounts:
            - name: differ-config
              mountPath: /code/config.yaml
              subPath: config.yaml

      volumes:
          - name: differ-config
            configMap:
              name: differ-config
              items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: differ-config
data:
  config.yaml: |
    namespace: "default"
    controllerSleep: "10s"
    metrics:
      port: 8080
      path: "/metrics"
    remotes:
      - provider: "github"
        reponame: "foo"
        username: "bar"

---
apiVersion: v1
kind: Service
metadata:
  name: difer-metrics
spec:
  type: ClusterIP
  selector:		
    app: differ
  ports:
  - name: metrics
    port: 9100
    targetPort: 8080
