apiVersion: apps/v1
kind: Deployment
metadata:
  name: differ-deployment
  annotations:
    differ/active: "true"
spec:
  selector:
    matchLabels:
      app: differ
  template:
    metadata:
      labels:
        app: differ
    spec:
      serviceAccountName: differ
      containers:
      - name: differ
        image: differ:dev
        args: ["--loglevel","debug"]
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        volumeMounts:
            - name: differ-config
              mountPath: /code/config.yaml
              subPath: config.yaml

      volumes:
          - name: differ-config
            configMap:
              name: differ-config
              items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: differ-config
data:
  config.yaml: |
    namespace: "default"
    controllerSleep: "10s"
    remotes:
      - provider: github
        reponame: foo
        username: bar