---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: differ-deployment
  annotations:
    differ/active: "true"
spec:
  selector:
    matchLabels:
      app: differ
  template:
    metadata:
      labels:
        app: differ
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccountName: differ
      containers:
      - name: differ
        image: differ:dev
        args: ["--loglevel","info"]
        ports:
        - containerPort: 8080
          name: metrics
        imagePullPolicy: Never
        volumeMounts:
            - name: differ-config
              mountPath: /code/config.yaml
              subPath: config.yaml
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        livenessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
          - name: differ-config
            configMap:
              name: differ-config
              items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: differ-config
data:
  config.yaml: |
    namespace: "default"
    controllerSleep: "10s"
    loglevel: "trace"
    metrics:
      port: 8080
      path: "/metrics"
    remotes:
      - provider: "github"
        reponame: "foo"
        username: "bar"

---
apiVersion: v1
kind: Service
metadata:
  name: difer-metrics
spec:
  type: ClusterIP
  selector:
    app: differ
  ports:
  - name: metrics
    port: 9100
    targetPort: 8080
