---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: differ-reader
rules:
- apiGroups: [""]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["*"] 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: differ
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-rolebinding
subjects:
- kind: ServiceAccount
  name: differ
roleRef:
  kind: Role
  name: differ-reader
  apiGroup: rbac.authorization.k8s.io