name: Go
on: [push, pull_request]
jobs:
  test:
    name: go-test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Go test with race and coverage
        uses: actions/setup-go@v2
        run: |
          go test -coverprofile=coverage.txt -race -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true

  lint:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Golangci-lint
        uses: actions-contrib/golangci-lint@v1

  build:
    name: go build
    runs-on: ubuntu-18.04
    needs: [test,lint]
    steps:
      - uses: actions/checkout@v2
      - name: Init go-semantic-release
        run: |
          wget  https://github.com/Nightapes/go-semantic-release/releases/download/1.4.1/go-semantic-release
          chmod +x go-semantic-release
      - name: Go build
          uses: actions/setup-go@v2
          run: |
            CGO_ENABLED=0 go build -o differ -ldflags ""-w -s -X main.version=$(./go-semantic-release next)"
      - name: Upload binary
          uses: actions/upload-artifact@v1
          with:
            name: go-build-binary
            path: differ
      - name: Upload binary semantic release
          uses: actions/upload-artifact@v1
          with:
            name: releaser-tool
            path: go-semantic-release

  build-docker:
    name: build docker images
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Download go-build binary
          uses: actions/download-artifact@v1
          with:
            name: go-build-binary
      - name: build-docker-latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wiedmannfelix/differ
          tags: latest

# TBD. ADD release